catalog/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'), #books/ (^ является маркером начала строки, а $ - маркер конца строки). Как было отмечено в предыдущей части руководства, URL-адрес уже должен содержать /catalog, таким образом полный адрес, на самом деле, имеет вид : /catalog/books/.
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'), #book/, за которым до конца строки (до маркера конца строки - $) следуют одна, или более цифр. В процессе выполнения данного преобразования, оно "захватывает" цифры и передаёт их в функцию отображения как параметр с именем pk.
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
    re_path(r'^book/(?P<pk>[-\w]+)/borrow/$', views.borrow_book, name='borrow_book'),
] 

urlpatterns += [
    re_path(r'^author/create/$', views.AuthorCreate.as_view(), name='author_create'),
    re_path(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author_update'),
    re_path(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author_delete'),
]

urlpatterns += [
    re_path(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    re_path(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book_update'),
    re_path(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book_delete'),
]

urlpatterns += [
    re_path(r'^book/create_book_instance/$', views.BookInstanceCreate.as_view(), name='book_instance_create'),
]

urlpatterns += [
    re_path(r'^genres/$', views.GenreListView.as_view(), name='genre_list'),
    re_path(r'^genre/create/$', views.GenreCreate.as_view(), name='genre_create'),
    re_path(r'^genre/delete/$', views.delete_genre, name='delete_genre'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.auth.views import LogoutView
from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.RegisterUser.as_view(), name='register'),
    path('accounts/profile/', views.ProfileView.as_view(), name='profile'),
    path('accounts/logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)), #RedirectView  принимает первым параметром новый относительный URL на который следует перенаправлять (/catalog/) когда указанный в функции url() адрес соотносится с адресом запроса (корневой URL, в данном случае).
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [path('catalog/', include('catalog.urls'))]  

catalog/models.py
from django.urls import reverse # Используется для генерации URL путем разворачивания URL-шаблонов
from django.db import models
from django.contrib.auth.models import User
from datetime import date
import uuid # Необходим для уникальных экземпляров книг

class Genre(models.Model):
    """
    Модель, представляющая жанр книги (например, Научная фантастика, Нон-фикшн).
    """
    name = models.CharField(max_length=200, help_text="Введите жанр книги (например, Научная фантастика, Французская поэзия и т.д.)")

    def get_absolute_url(self):
        """
        Возвращает URL для доступа к определенному экземпляру жанра.
        """
        return reverse('genre_list')

    def __str__(self):
        """
        Строка для представления объекта модели (в админке и т.д.)
        """
        return self.name

class Book(models.Model):
    """
    Модель, представляющая книгу (но не конкретный экземпляр книги).
    """
    image = models.ImageField(null=True, blank=True,default='default.jpg', upload_to='Books')
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Введите краткое описание книги")
    isbn = models.CharField('ISBN',max_length=13, help_text='13-значный номер <a href="https://www.isbn-international.org/content/what-isbn">ISBN</a>')
    genre = models.ManyToManyField(Genre, help_text="Выберите жанры для этой книги")

    def __str__(self):
        """
        Строка для представления объекта модели.
        """
        return self.title

    def get_absolute_url(self):
        """
        Возвращает URL для доступа к определенному экземпляру книги.
        """
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        """
        Создает строку для жанра. Необходимо для отображения жанра в админке.
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
    display_genre.short_description = 'Жанр'
    
class BookInstance(models.Model):
    """
    Модель, представляющая конкретный экземпляр книги (т.е. который можно взять в библиотеке).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Уникальный идентификатор для данной книги в библиотеке")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True, help_text="Дата возврата")
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    LOAN_STATUS = (
        ('m', 'Обслуживание'),
        ('o', 'Выдана'),
        ('a', 'Доступна'),
        ('r', 'Зарезервирована'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Доступность книги')

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Установка статуса 'Возвращена'"),)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def get_absolute_url(self):
        """
        Возвращает URL для доступа к определенному экземпляру книги.
        """
        return reverse('book_instance_create')

    def __str__(self):
        """
        Строка для представления объекта модели.
        """
        return '%s (%s)' % (self.id,self.book.title)

class Author(models.Model):
    """
    Модель, представляющая автора.
    """
    image = models.ImageField(null=True, blank=True,default='default.jpg', upload_to='Authors')
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True, help_text="Дата рождения")
    date_of_death = models.DateField('Умер', null=True, blank=True, help_text="Дата смерти")
    about_the_author = models.TextField(max_length=1000)

    def get_absolute_url(self):
        """
        Возвращает URL для доступа к определенному экземпляру автора.
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """
        Строка для представления объекта модели.
        """
        return '%s, %s' % (self.last_name, self.first_name)
    
    class Meta:
        ordering = ['last_name']
        permissions = (
                ("can_change_author", "Изменение автора"),
        )

catalog/views.py
from django.shortcuts import render
from .models import Book, Author, BookInstance, Genre
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
    # Генерация "количеств" некоторых главных объектов
    books = Book.objects.all()[:5] 
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    num_genres = Genre.objects.all().count()
    num_books_word = Book.objects.filter(title__icontains='Убить').count()
    # Доступные книги (статус = 'a')
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()  # Метод 'all()' применён по умолчанию.

    # Отрисовка HTML-шаблона index.html с данными внутри
    # переменной контекста context
    return render(
        request,
        'index.html',
        context={'book_list': books,'num_books_word': num_books_word,'num_genres': num_genres,'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors},
    )

from django.views import generic

class BookListView(generic.ListView):
    model = Book

    paginate_by = 14

    def get_context_data(self, **kwargs):
        # В первую очередь получаем базовую реализацию контекста
        context = super(BookListView, self).get_context_data(**kwargs)
        # Добавляем новую переменную к контексту и инициализируем её некоторым значением
        context['some_data'] = 'This is just some data'
        return context
    
class BookDetailView(generic.DetailView):
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_librarian'] = self.request.user.groups.filter(name='Библиотекари').exists()
        return context

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_librarian'] = self.request.user.groups.filter(name='Библиотекари').exists()
        return context

class ProfileView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing books on loan to current user.
    """
    model = BookInstance
    template_name ='catalog/profile.html'


    def get_queryset(self):
        if self.request.user.groups.filter(name='Библиотекари').exists():
        # Если пользователь принадлежит к группе 'Библиотекари', то
        # отображаем все зарезервированные книги
            return BookInstance.objects.filter(status__exact='o').order_by('due_back')
        else:
        # Если пользователь не принадлежит к группе 'Библиотекари', то
        # отображаем только зарезервированные книги текущего пользователя
            return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_librarian'] = self.request.user.groups.filter(name='Библиотекари').exists()
        return context

from django.contrib.auth.decorators import permission_required

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime

from .forms import RenewBookForm, RegisterUserForm

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime

from .forms import RenewBookForm
from .forms import BookCreateForm
from .forms import BookInstanceCreateForm
from .forms import AuthorCreateForm
from .forms import AuthorUpdateForm
from .forms import GenreCreateForm
from .models import Book
from django.urls import reverse_lazy

def renew_book_librarian(request, pk):
    book_inst = get_object_or_404(BookInstance, pk=pk)

    # Если данный запрос типа POST, тогда
    if request.method == 'POST':

        # Создаём экземпляр формы и заполняем данными из запроса (связывание, binding):
        form = RenewBookForm(request.POST)

        # Проверка валидности данных формы:
        if form.is_valid():
            # Обработка данных из form.cleaned_data
            #(здесь мы просто присваиваем их полю due_back)
            book_inst.due_back = form.cleaned_data['due_back']
            book_inst.save()

            # Переход по адресу 'all-borrowed':
            return HttpResponseRedirect(reverse('profile') )

    # Если это GET (или какой-либо ещё), создать форму по умолчанию.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})

def borrow_book(request, pk):
    copy = get_object_or_404(BookInstance,  pk=pk)

    if request.method == 'POST':
        copy.status = 'o'
        copy.borrower = request.user  # сохраняем пользователя
        copy.save()
        return HttpResponseRedirect(reverse('book-detail', args=[copy.book.pk]))

    return render(request, 'catalog/borrow_book.html', {'copy': copy})


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Author

from django.contrib.auth.mixins import PermissionRequiredMixin

class AuthorCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Author
    form_class = AuthorCreateForm
    initial = {'date_of_death': 'xx.xx.xxxx'}
    permission_required = 'catalog.can_change_author'

class AuthorUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Author
    form_class = AuthorUpdateForm
    permission_required = 'catalog.can_change_author'

class AuthorDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.can_change_author'

class BookCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Book
    form_class = BookCreateForm
    permission_required = 'catalog.can_change_author'

class BookUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Book
    fields = ['image','title','author','summary','isbn', 'genre']
    permission_required = 'catalog.can_change_author'

class BookDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    permission_required = 'catalog.can_change_author'

class BookInstanceCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = BookInstance
    form_class = BookInstanceCreateForm
    permission_required = 'catalog.can_change_author'

    def get_success_url(self):
        # Получаем id книги, к которой добавили экземпляр
        book_id = self.object.book.id
        # Формируем URL страницы книги
        return reverse_lazy('book-detail', kwargs={'pk': book_id})

class GenreCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Genre
    form_class = GenreCreateForm
    permission_required = 'catalog.can_change_author'

class GenreListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    model = Genre
    permission_required = 'catalog.can_change_author'

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt # чтобы обойти проверку CSRF-токена во время разработки и настроили обработчик POST-запроса на удаление жанра из бд

@csrf_exempt
def delete_genre(request):
    if request.method == 'POST':
        genre_id = request.POST.get('genre_id')
        genre = Genre.objects.get(pk=genre_id)
        genre.delete()
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False})
    
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

   

catalog/templates/catalog/author_List.html
{% extends "base_generic.html" %}
{% block content %}
<style>
  .author-list {
  list-style-type: none;
  padding: 0;
}

.author-item {
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}

.author-avatar {
  margin-right: 10px;
  width: 50px; /* Ширина аватара */
  height: 50px; /* Высота аватара */
  overflow: hidden;
  border-radius: 50%; /* Округление аватара */
}

.author-avatar img {
  width: 100%;
  height: auto;
  display: block;
}

.author-info {
  flex: 1;
}
</style>
{% if author_list %}
<div class="__container">
  <ul class="author-list">
    {% for author in author_list %}
    <li>
      <div class="author-item">
        <div class="author-avatar">
          <img src="{{ author.image.url }}" alt="{{ author.first_name }} {{ author.last_name }} Avatar">
        </div>
        <div class="author-info">
          <a href="{% url 'author-detail' author.pk %}">
            {{ author.last_name }}, {{ author.first_name }}
          </a>
        </div>
      </div>
    </li>
    {% endfor %}
  </ul>
</div> 
{% else %}
  <p>В библиотеке нет авторов</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="__container">
    <h1>Удалить автора</h1>

    <p>Вы уверены, что хотите удалить автора: {{ author }}?</p>

    <form action="" method="POST">
    {% csrf_token %}
    <input class="default_btn btn" type="submit" value="Да, удалить." />
    </form>
</div>
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="__container">
  <div class="block-detail">
    <div class="block-detail__img book__image">
      <img src="{{ author.image.url }}" alt="";>
    </div>
    <div class="block-detail__body">
      <div class="block-detail__title title">
        {{ author.last_name }}, {{ author.first_name }}
      </div>
        <ul class="block-detail__info">
          {% if author.date_of_death %}
          <li><span class="subtitle">Годы жизни:</span> <p>{{ author.date_of_birth }} - {{ author.date_of_death }}</p></li>
        {% else %}
          <li><span class="subtitle">Годы жизни:</span> <p>{{ author.date_of_birth }} - По настоящее время</p></li>
        {% endif %}
          <li class="about-the-author"><span class="subtitle">Биография:</span> <p>{{ author.about_the_author }}</p></li>
      </div>
    </div>
    {% if is_librarian  %}
      <div class="menu-controll">
          <a href="{% url 'author_update' author.pk %}" class="btn editing_btn">Редактировать</a>
          <a href="{% url 'author_delete' author.pk %}" class="btn delete_btn">Удалить</a> 
      </div>
    {% endif %}
</div>


{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}
{% if perms.catalog.can_mark_returned %}
    {% block content %}
<div class="__container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input class="default_btn btn" type="submit" value="Отправить" />
    
    </form>
</div>
{% endblock %}
{% endif %}

catalog/templates/catalog/book_List.html
{% extends "base_generic.html" %}

{% block content %}
    {% if book_list %}
      <div class="book-list __container">
        {% for book in book_list %}
        <div class="book__card">
            <div class="book__image"><a href="{{ book.get_absolute_url }}"><img src="{{ book.image.url }}" alt="book_image"></a></div>
            <p class="book__title">{{ book.title }}</p>
            <a class="book__author" href="">
              {{ book.author }}
            </a>
        </div>
        {% endfor %}
      </div>
    {% else %}
      <p>В библиотеке нет книг</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="__container">
    <h1>Удалить книгу</h1>

    <p>Вы уверены, что хотите удалить книгу {{ book }}?</p>

    <form action="" method="POST">
    {% csrf_token %}
    <input class="default_btn btn" type="submit" value="Да, удалить." />
    </form>
</div>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="__container">
  <div class="block-detail">
    <div class="block-detail__img book__image">
      <img src="{{ book.image.url }}" alt="";>
    </div>
    <div class="block-detail__body">
      <div class="block-detail__title title">
        {{ book.title }}
      </div>
        <ul class="block-detail__info">
          <li class="book-detail__author"><span class="subtitle">Автор:</span><a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></li>
          <li><span class="subtitle">Описание:</span> <p class="book-detail__description">{{ book.summary }}</p></li>
          <li><span class="subtitle">Жанр:</span>{% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
          <li><span class="subtitle">ISBN:</span>{{ book.isbn }}</li>
        </ul>
      </div>
    </div>
    {% if is_librarian  %}
        <div class="menu-controll">
            <a href="{% url 'book_update' book.pk %}" class="btn editing_btn">Редактировать</a>
            <a href="{% url 'book_delete' book.pk %}" class="btn delete_btn">Удалить</a> 
        </div>
    {% endif %}
    {% if user.is_authenticated %}
    <div style="margin-left:20px;margin-top:20px">
      <h4>Копии</h4>
      {% for copy in book.bookinstance_set.all %} 
      {# /*Данный метод является "автомагически"-сконструированным Django для того, чтобы вернуть множество записей BookInstance, связанных с данной книгой Book. bookinstance, за которым следует _set (то есть функция, созданная для Book будет иметь вид bookinstance_set()).*\ #}                                            
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
        {% if copy.status != 'a' %}<p><strong>Возврат книги:</strong> {{copy.due_back}}</p>{% endif %}
        <p><strong>Imprint:</strong> {{copy.imprint}}</p>
        <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
        <a class="{% if copy.status == 'a' %}borrowed__btn{% else %}dn{% endif %}" href="{% url 'borrow_book' copy.pk %}">Забронировать</a>
      {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}
{% if perms.catalog.can_mark_returned %}
    {% block content %}
<div class="__container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input class="default_btn btn" type="submit" value="Отправить" />
    
    </form>
</div>
{% endblock %}
{% endif %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}
    <div class="__container">
        <h1>Название книги: {{bookinst.book.title}}</h1>
        <p>Заемщик: {{bookinst.borrower}}</p>
        <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Дата возврата: {{bookinst.due_back}}</p>

        <form action="" method="post">
            {% csrf_token %}
            <table>
            {{ form }}
            </table>
            <input class="btn default_btn" type="submit" value="Продлить" />
        </form>
    </div>
    

{% endblock %}

catalog/templates/catalog/bookinstance_form.html
{% extends "base_generic.html" %}
{% if perms.catalog.can_mark_returned %}
    {% block content %}
<div class="__container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input class="default_btn btn" type="submit" value="Отправить" />
    
    </form>
</div>
{% endblock %}
{% endif %}

catalog/templates/catalog/borrow_book.html
{% extends "base_generic.html" %}

{% block content %}
<div class="__container">
    <h1>Забронировать книгу "{{ copy.book.title }}"</h1>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn default_btn">Забронировать книгу</button>
  </form>
</div>
{% endblock %}

catalog/templates/catalog/genre_form.html
{% extends "base_generic.html" %}
{% if perms.catalog.can_mark_returned %}
    {% block content %}
<div class="__container">
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input class="default_btn btn" type="submit" value="Добавить" />
    
    </form>
</div>
{% endblock %}
{% endif %}

catalog/templates/catalog/genre_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="__container">
    {% if genre_list %}
    <div class="__container">
      <ul class="author-list">
        {% for genre in genre_list %}
        <li id="genre-{{ genre.pk }}">{{ genre }} <button class="btn-delete" data-id="{{ genre.pk }}"><i class="fa-solid fa-trash" style="color: #FF5D5D;"></i></button></li>
        {% endfor %}
      </ul>
    </div> 
    {% else %}
      <p>Список жанров пуст</p>
    {% endif %}
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    $('.btn-delete').click(function() {
        var genreId = $(this).data('id');
        $.ajax({
            url: '{% url "delete_genre" %}',
            method: 'POST',
            data: { genre_id: genreId },
            success: function(response) {
                $('#genre-' + genreId).remove();
            }
        });
    });
});
</script>
{% endblock %}

catalog/templates/catalog/profile.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
    <div class="account __container">
      <div class="profile">
          <h2>Профиль</h1>
            <div class="profile-header">
              <div class="profile__image">
                <img src="{% static 'img/default.jpg' %}" alt="">
              </div>
              <div class="profile-header__info">

                {% if is_librarian  %}
                  <p class="profile__status" style="color: #FAD55E;">библиотекарь</p>
                {% else %}
                  <p class="profile__status">пользователь</p>
                {% endif %}
                
                <p class="profile__name">{{ user.get_username }}</p>
              </div>
            </div>
            <!-- <ul class="profile__info">
                <li>Дата рождения: <span class="date-of-birth"></span></li>
                <li>Email: <span class="email">1312321@gmail.com</span></li>
            </ul> -->
            <div class="profile__dictation">
              <a class=" btn" href="#">Редактировать</a>
            </div>
        
      </div>

      {% if is_librarian  %}
        <div class="">
          <h2>Спец. Возможности</h1>
            <ul>
              <li><a href="{% url 'author_create' %}">Добавить автора</a></li>
              <li><a href="{% url 'book_create' %}">Добавить книгу</a></li>
              <li><a href="{% url 'book_instance_create' %}">Добавить копию для книги</a></li>
              <li><a href="{% url 'genre_create' %}">Добавить жанр</a></li>
              <li><a href="{% url 'genre_list' %}">Все жанры</a></li>
            </ul>
        </div>
      {% endif %}

      <div class="">
        <h2>Забронированные книги</h1>
          {% if bookinstance_list %}
          <ul>
      
            {% for bookinst in bookinstance_list %}
            {% if is_librarian  %}
                <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                  <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) - {{ bookinst.borrower }} - <a href="{% url 'renew-book-librarian' bookinst.id %}">Продлить</a> 
            {% else %}
                <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                  <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
                </li>
            {% endif %}
            {% endfor %}
          </ul>
      </div>
      
    </div>
    

    {% else %}
      <p>У вас нет книг в прокате.</p>
    {% endif %}
{% endblock %}